title: Robot Teleoperation Platform
email: kevinwelsh132@gmail.com
github_username: kpwelsh

source: _docs

theme: just-the-docs
color_scheme: dark
scholar:
  style: modern-language-association

markdown: kramdown
highlighter: rouge